# name
name: hello_world

# trigger
on:
- push

# one or more jobs
jobs:
    greetings:
        runs-on: ubuntu-latest
        steps:
          - id: s00
            run: echo "current time in Github $(date)"
          - id: s01
            uses: mscoutermarsh/cowsay-action@master
            with:
                text: 'ship ship ship!'
                color: 'blue'
        #   - id: s01
        #     run: ls -la